<?php

namespace Hn7r\Bible\Constant;

use Hn7r\Bible\Constant\Book as BookConstant;
use Hn7r\Bible\Enum\Book;

class Verse
{
    public const array VERSES_PER_CHAPTER = [
        Book::Genesis->value => BookConstant\Genesis::VERSES_PER_CHAPTER,
        Book::Exodus->value => BookConstant\Exodus::VERSES_PER_CHAPTER,
        Book::Leviticus->value => BookConstant\Leviticus::VERSES_PER_CHAPTER,
        Book::Numbers->value => BookConstant\Numbers::VERSES_PER_CHAPTER,
        Book::Deuteronomy->value => BookConstant\Deuteronomy::VERSES_PER_CHAPTER,
        Book::Joshua->value => BookConstant\Joshua::VERSES_PER_CHAPTER,
        Book::Judges->value => BookConstant\Judges::VERSES_PER_CHAPTER,
        Book::Ruth->value => BookConstant\Ruth::VERSES_PER_CHAPTER,
        Book::FirstSamuel->value => BookConstant\FirstSamuel::VERSES_PER_CHAPTER,
        Book::SecondSamuel->value => BookConstant\SecondSamuel::VERSES_PER_CHAPTER,
        Book::FirstKings->value => BookConstant\FirstKings::VERSES_PER_CHAPTER,
        Book::SecondKings->value => BookConstant\SecondKings::VERSES_PER_CHAPTER,
        Book::FirstChronicles->value => BookConstant\FirstChronicles::VERSES_PER_CHAPTER,
        Book::SecondChronicles->value => BookConstant\SecondChronicles::VERSES_PER_CHAPTER,
        Book::Ezra->value => BookConstant\Ezra::VERSES_PER_CHAPTER,
        Book::Nehemiah->value => BookConstant\Nehemiah::VERSES_PER_CHAPTER,
        Book::Esther->value => BookConstant\Esther::VERSES_PER_CHAPTER,
        Book::Job->value => BookConstant\Job::VERSES_PER_CHAPTER,
        Book::Psalms->value => BookConstant\Psalms::VERSES_PER_CHAPTER,
        Book::Proverbs->value => BookConstant\Proverbs::VERSES_PER_CHAPTER,
        Book::Ecclesiastes->value => BookConstant\Ecclesiastes::VERSES_PER_CHAPTER,
        Book::SongOfSolomon->value => BookConstant\SongOfSolomon::VERSES_PER_CHAPTER,
        Book::Isaiah->value => BookConstant\Isaiah::VERSES_PER_CHAPTER,
        Book::Jeremiah->value => BookConstant\Jeremiah::VERSES_PER_CHAPTER,
        Book::Lamentations->value => BookConstant\Lamentations::VERSES_PER_CHAPTER,
        Book::Ezekiel->value => BookConstant\Ezekiel::VERSES_PER_CHAPTER,
        Book::Daniel->value => BookConstant\Daniel::VERSES_PER_CHAPTER,
        Book::Hosea->value => BookConstant\Hosea::VERSES_PER_CHAPTER,
        Book::Joel->value => BookConstant\Joel::VERSES_PER_CHAPTER,
        Book::Amos->value => BookConstant\Amos::VERSES_PER_CHAPTER,
        Book::Obadiah->value => BookConstant\Obadiah::VERSES_PER_CHAPTER,
        Book::Jonah->value => BookConstant\Jonah::VERSES_PER_CHAPTER,
        Book::Micah->value => BookConstant\Micah::VERSES_PER_CHAPTER,
        Book::Nahum->value => BookConstant\Nahum::VERSES_PER_CHAPTER,
        Book::Habakkuk->value => BookConstant\Habakkuk::VERSES_PER_CHAPTER,
        Book::Zephaniah->value => BookConstant\Zephaniah::VERSES_PER_CHAPTER,
        Book::Haggai->value => BookConstant\Haggai::VERSES_PER_CHAPTER,
        Book::Zechariah->value => BookConstant\Zechariah::VERSES_PER_CHAPTER,
        Book::Malachi->value => BookConstant\Malachi::VERSES_PER_CHAPTER,
        Book::Matthew->value => BookConstant\Matthew::VERSES_PER_CHAPTER,
        Book::Mark->value => BookConstant\Mark::VERSES_PER_CHAPTER,
        Book::Luke->value => BookConstant\Luke::VERSES_PER_CHAPTER,
        Book::John->value => BookConstant\John::VERSES_PER_CHAPTER,
        Book::Acts->value => BookConstant\Acts::VERSES_PER_CHAPTER,
        Book::Romans->value => BookConstant\Romans::VERSES_PER_CHAPTER,
        Book::FirstCorinthians->value => BookConstant\FirstCorinthians::VERSES_PER_CHAPTER,
        Book::SecondCorinthians->value => BookConstant\SecondCorinthians::VERSES_PER_CHAPTER,
        Book::Galatians->value => BookConstant\Galatians::VERSES_PER_CHAPTER,
        Book::Ephesians->value => BookConstant\Ephesians::VERSES_PER_CHAPTER,
        Book::Philippians->value => BookConstant\Philippians::VERSES_PER_CHAPTER,
        Book::Colossians->value => BookConstant\Colossians::VERSES_PER_CHAPTER,
        Book::FirstThessalonians->value => BookConstant\FirstThessalonians::VERSES_PER_CHAPTER,
        Book::SecondThessalonians->value => BookConstant\SecondThessalonians::VERSES_PER_CHAPTER,
        Book::FirstTimothy->value => BookConstant\FirstTimothy::VERSES_PER_CHAPTER,
        Book::SecondTimothy->value => BookConstant\SecondTimothy::VERSES_PER_CHAPTER,
        Book::Titus->value => BookConstant\Titus::VERSES_PER_CHAPTER,
        Book::Philemon->value => BookConstant\Philemon::VERSES_PER_CHAPTER,
        Book::Hebrews->value => BookConstant\Hebrews::VERSES_PER_CHAPTER,
        Book::James->value => BookConstant\James::VERSES_PER_CHAPTER,
        Book::FirstPeter->value => BookConstant\FirstPeter::VERSES_PER_CHAPTER,
        Book::SecondPeter->value => BookConstant\SecondPeter::VERSES_PER_CHAPTER,
        Book::FirstJohn->value => BookConstant\FirstJohn::VERSES_PER_CHAPTER,
        Book::SecondJohn->value => BookConstant\SecondJohn::VERSES_PER_CHAPTER,
        Book::ThirdJohn->value => BookConstant\ThirdJohn::VERSES_PER_CHAPTER,
        Book::Jude->value => BookConstant\Jude::VERSES_PER_CHAPTER,
        Book::Revelation->value => BookConstant\Revelation::VERSES_PER_CHAPTER,
    ];
}
